#ifndef ENN_DEVICE_TYPE_H
#define ENN_DEVICE_TYPE_H


//水表
#define ENN_DEVICE_TYPE_WATERMETER "0008"

//电表
#define ENN_DEVICE_TYPE_POWERMETER "0007"

//三控开关
#define ENN_DEVICE_TYPE_ON_OFF_THREE "0016"

//窗帘 
#define ENN_DEVICE_TYPE_WINDOWS "0002"

//可调亮度色温灯 
#define ENN_DEVICE_TYPE_COLOR_TEMP_LAMP "0015"

//温湿度 
#define ENN_DEVICE_TYPE_TEMP_HUM "0009"

//燃气报警
#define ENN_DEVICE_TYPE_GAS "0005"

//甲醛报警
#define ENN_DEVICE_TYPE_GAS "0004"

//PM2.5
#define ENN_DEVICE_TYPE_GAS "0003"

//烟雾
#define ENN_DEVICE_TYPE_GAS "0006"

#endif