#ifndef ENN_DEVICE_TYPE_H
#define ENN_DEVICE_TYPE_H

//UEM泛能机
#define ENN_DEVICE_TYPE_GATEWAY "0001"

//水表
#define ENN_DEVICE_TYPE_WATERMETER "0006"

//电表
#define ENN_DEVICE_TYPE_POWERMETER "0005"

//开关
#define ENN_DEVICE_TYPE_ON_OFF_THREE "0009"

//窗帘 
#define ENN_DEVICE_TYPE_WINDOWS "0036"

//可调亮度灯 
#define ENN_DEVICE_TYPE_BRIGHTNESS_LAMP "0018"

//可调亮度色温灯 
#define ENN_DEVICE_TYPE_COLOR_TEMP_LAMP "0037"

//温湿度 
#define ENN_DEVICE_TYPE_TEMP_HUM "0038"

//燃气报警
#define ENN_DEVICE_TYPE_GAS "0039"

#endif