#ifndef ENN_DEVICE_TYPE_H
#define ENN_DEVICE_TYPE_H
//窗帘 
#define ENN_DEVICE_TYPE_WINDOWS 2
//PM2.5
#define ENN_DEVICE_TYPE_PM25 3
//甲醛报警
#define ENN_DEVICE_TYPE_FORMAL 4
//燃气报警
#define ENN_DEVICE_TYPE_GAS 5
//烟雾
#define ENN_DEVICE_TYPE_SMOKE 6
//电表
#define ENN_DEVICE_TYPE_POWERMETER 7

//水表
#define ENN_DEVICE_TYPE_WATERMETER 8
//温湿度 
#define ENN_DEVICE_TYPE_TEMP_HUM 9
//可调亮度色温灯 
#define ENN_DEVICE_TYPE_COLOR_TEMP_LAMP 15

//三控开关
#define ENN_DEVICE_TYPE_ON_OFF_THREE 6

//开关插座
#define ENN_DEVICE_TYPE_POWER_OUTLET 17

//门磁
#define ENN_DEVICE_TYPE_MAGNETIC_DOOR 18
//人体红外
#define ENN_DEVICE_TYPE_BODY_INFRARED 19
//燃气表
#define ENN_DEVICE_TYPE_GAS_METER 20
//热表
#define ENN_DEVICE_TYPE_HEAT_METER 21


#endif
